// ============================================================
// LOCATION STALENESS JOB — Every hour
// Flags CHECKED_OUT equipment with no GPS ping in 2+ hours
// ============================================================
const { pool }         = require('../config/database');
const { LOCATION_QUERIES } = require('../queries/location.queries');
const alertService     = require('../services/alert.service');
const { ALERT_TYPES }  = require('../constants/alertTypes');
const logger           = require('../config/logger');

async function runLocationStaleness() {
  try {
    const { rows } = await pool.query(LOCATION_QUERIES.STALE_EQUIPMENT);

    for (const eq of rows) {
      await alertService.createAlert({
        type:        ALERT_TYPES.EQUIPMENT_MISSING,
        severity:    'HIGH',
        title:       `Location Unknown: ${eq.name}`,
        message:     `Equipment ${eq.serial_number} has not sent a GPS ping in over 2 hours`,
        equipmentId: eq.id,
        baseId:      eq.base_id,
        autoGenerated: true,
      });
    }

    if (rows.length > 0) logger.warn(`Location staleness: ${rows.length} equipment flagged`);
  } catch (err) {
    logger.error('Location staleness job failed', { error: err.message });
  }
}

module.exports = { runLocationStaleness };
