// ============================================================
// MAINTENANCE REMINDER JOB — Every day at midnight
// ============================================================
const { pool }         = require('../config/database');
const { EQUIPMENT_QUERIES } = require('../queries/equipment.queries');
const alertService     = require('../services/alert.service');
const { ALERT_TYPES }  = require('../constants/alertTypes');
const logger           = require('../config/logger');

async function runMaintenanceReminder() {
  try {
    const { rows } = await pool.query(EQUIPMENT_QUERIES.DUE_FOR_MAINTENANCE);

    for (const eq of rows) {
      await alertService.createAlert({
        type:        ALERT_TYPES.MAINTENANCE_DUE,
        severity:    'MEDIUM',
        title:       `Maintenance Due: ${eq.name}`,
        message:     `Equipment ${eq.serial_number} is due for maintenance on ${eq.next_maintenance_due}`,
        equipmentId: eq.id,
        baseId:      eq.base_id,
        autoGenerated: true,
        metadata:    { next_maintenance_due: eq.next_maintenance_due },
      });
    }

    logger.info(`Maintenance reminder: ${rows.length} alerts created`);
  } catch (err) {
    logger.error('Maintenance reminder job failed', { error: err.message });
  }
}

module.exports = { runMaintenanceReminder };
