// ============================================================
// OVERDUE DETECTION JOB — Every 5 minutes
// Marks overdue checkouts, creates alerts, emits WebSocket events
// ============================================================
const { pool }         = require('../config/database');
const { CHECKOUT_QUERIES } = require('../queries/checkout.queries');
const alertService     = require('../services/alert.service');
const { emitCheckoutOverdue } = require('../events/emitters');
const { ALERT_TYPES }  = require('../constants/alertTypes');
const logger           = require('../config/logger');

async function runOverdueDetection() {
  try {
    const { rows: overdueRows } = await pool.query(CHECKOUT_QUERIES.MARK_OVERDUE);

    for (const row of overdueRows) {
      logger.info('Checkout marked overdue', { checkoutId: row.id, equipment: row.equipment_name });

      // Get base id from equipment
      const { rows: eRows } = await pool.query(
        'SELECT home_base_id FROM equipment WHERE id = $1', [row.equipment_id]
      );
      const baseId = eRows[0]?.home_base_id;

      await alertService.createAlert({
        type:        ALERT_TYPES.OVERDUE_RETURN,
        severity:    'HIGH',
        title:       `Overdue Return: ${row.equipment_name}`,
        message:     `${row.checked_out_by_name} has not returned ${row.equipment_name} (due: ${row.expected_return_at})`,
        equipmentId: row.equipment_id,
        personnelId: row.checked_out_by_id,
        checkoutId:  row.id,
        baseId,
        assigneeId:  row.checked_out_by_id,
        autoGenerated: true,
      });

      emitCheckoutOverdue(baseId, {
        checkoutId:   row.id,
        equipmentId:  row.equipment_id,
        equipmentName: row.equipment_name,
        soldierName:  row.checked_out_by_name,
        expected:     row.expected_return_at,
      });
    }

    // 2. STOLEN Incident Escalation (2 hours)
    const { rows: stolenRows } = await pool.query(`
      SELECT id, incident_number, title, created_at, base_id 
      FROM incident_reports 
      WHERE type = 'STOLEN' AND status = 'OPEN' 
      AND created_at < NOW() - INTERVAL '2 hours' 
      AND co_acknowledged_at IS NULL
    `);

    for (const row of stolenRows) {
      logger.warn('STOLEN incident escalation triggered', { incidentId: row.id, number: row.incident_number });

      await alertService.createAlert({
        type:        'STOLEN_INCIDENT_ESCALATED',
        severity:    'CRITICAL',
        title:       `ESCALATION: Stolen Asset ${row.incident_number}`,
        message:     `Incident ${row.incident_number} remains unacknowledged by CO after 2 hours. Mandatory escalation.`,
        baseId:      row.base_id,
        autoGenerated: true,
      });

      // Update incident status
      await pool.query(
        "UPDATE incident_reports SET status = 'ESCALATED', updated_at = NOW() WHERE id = $1", [row.id]
      );
    }

    if (overdueRows.length > 0 || stolenRows.length > 0) {
      logger.info(`Job complete: ${overdueRows.length} overdue, ${stolenRows.length} stolen escalated`);
    }
  } catch (err) {
    logger.error('Overdue detection job failed', { error: err.message });
  }
}

module.exports = { runOverdueDetection };
