// ============================================================
// ALERT SERVICE — Full implementation with stats + total
// ============================================================

const { pool }         = require('../config/database');
const { ALERT_STATUS, ALERT_SEVERITY } = require('../constants/statusTypes');
const { ALERT_TYPES }  = require('../constants/alertTypes');
const { emitAlertCreated, emitAlertUpdated } = require('../events/emitters');
const logger           = require('../config/logger');

// ── createAlert ───────────────────────────────────────────────

async function createAlert({ type, severity, title, message, equipmentId, personnelId, checkoutId, baseId, assigneeId, metadata, autoGenerated = true }) {
  const { rows } = await pool.query(
    `INSERT INTO alerts (type, severity, title, message,
       equipment_id, personnel_id, checkout_id, base_id,
       assignee_id, metadata, auto_generated, status)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'OPEN')
     RETURNING *`,
    [type, severity, title, message, equipmentId || null, personnelId || null,
     checkoutId || null, baseId || null, assigneeId || null,
     metadata ? JSON.stringify(metadata) : null, autoGenerated]
  );
  const alert = rows[0];
  if (baseId) emitAlertCreated(baseId, alert, assigneeId);
  return alert;
}

// ── list ──────────────────────────────────────────────────────

async function listAlerts({ page = 1, limit = 20, status, severity, type, baseId, is_anomaly } = {}) {
  const params = [];
  let pIdx = 1;
  let where = '';

  if (status)    { where += ` AND a.status = $${pIdx++}`;       params.push(status); }
  if (severity)  { where += ` AND a.severity = $${pIdx++}`;     params.push(severity); }
  if (type)      { where += ` AND a.type = $${pIdx++}`;         params.push(type); }
  if (baseId)    { where += ` AND a.base_id = $${pIdx++}`;      params.push(baseId); }

  const offset = (Math.max(1, page) - 1) * limit;

  const dataSql = `
    SELECT
      a.*,
      e.name AS equipment_name, e.serial_number,
      p.full_name AS personnel_name,
      ack.full_name AS acknowledged_by_name,
      res.full_name AS resolved_by_name,
      asgn.full_name AS assigned_to_name
    FROM alerts a
    LEFT JOIN equipment e  ON e.id  = a.equipment_id
    LEFT JOIN personnel p  ON p.id  = a.personnel_id
    LEFT JOIN personnel ack ON ack.id = a.acknowledged_by_id
    LEFT JOIN personnel res ON res.id = a.resolved_by_id
    LEFT JOIN personnel asgn ON asgn.id = a.assignee_id
    WHERE 1=1 ${where}
    ORDER BY
      CASE a.severity WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END,
      a.created_at DESC
    LIMIT $${pIdx++} OFFSET $${pIdx++}
  `;

  const countSql = `SELECT COUNT(*) FROM alerts a WHERE 1=1 ${where}`;

  // Stats (always scoped to base)
  const statsSql = `
    SELECT
      COUNT(*) FILTER (WHERE status='OPEN')         AS open,
      COUNT(*) FILTER (WHERE status='ACKNOWLEDGED') AS acknowledged,
      COUNT(*) FILTER (WHERE status='RESOLVED')     AS resolved,
      COUNT(*) FILTER (WHERE status='DISMISSED')    AS dismissed,
      0 AS anomalies
    FROM alerts a
    WHERE 1=1 ${baseId ? ` AND a.base_id = $1` : ''}
  `;

  const [{ rows }, { rows: countRows }, { rows: statsRows }] = await Promise.all([
    pool.query(dataSql, [...params, limit, offset]),
    pool.query(countSql, params),
    pool.query(statsSql, baseId ? [baseId] : []),
  ]);

  return {
    data:  rows,
    total: parseInt(countRows[0].count),
    stats: {
      open:         parseInt(statsRows[0].open),
      acknowledged: parseInt(statsRows[0].acknowledged),
      resolved:     parseInt(statsRows[0].resolved),
      dismissed:    parseInt(statsRows[0].dismissed),
      anomalies:    parseInt(statsRows[0].anomalies),
    },
  };
}

// ── acknowledge / resolve / dismiss ──────────────────────────

async function acknowledgeAlert(id, user) {
  const { rows } = await pool.query(
    `UPDATE alerts SET status = 'ACKNOWLEDGED', acknowledged_by_id = $2, acknowledged_at = NOW()
     WHERE id = $1 AND status = 'OPEN' RETURNING *`,
    [id, user.id]
  );
  if (!rows[0]) throw Object.assign(new Error('Alert not found or already acknowledged'), { statusCode: 404 });
  emitAlertUpdated(rows[0].base_id, rows[0]);
  return rows[0];
}

async function resolveAlert(id, user, resolution_notes) {
  const { rows } = await pool.query(
    `UPDATE alerts SET status = 'RESOLVED', resolved_by_id = $2, resolved_at = NOW(),
       resolution_notes = $3
     WHERE id = $1 RETURNING *`,
    [id, user.id, resolution_notes]
  );
  if (!rows[0]) throw Object.assign(new Error('Alert not found'), { statusCode: 404 });
  emitAlertUpdated(rows[0].base_id, rows[0]);
  return rows[0];
}

async function dismissAlert(id, user) {
  const { rows } = await pool.query(
    `UPDATE alerts SET status = 'DISMISSED' WHERE id = $1 RETURNING *`, [id]
  );
  if (!rows[0]) throw Object.assign(new Error('Alert not found'), { statusCode: 404 });
  return rows[0];
}

module.exports = { createAlert, listAlerts, acknowledgeAlert, resolveAlert, dismissAlert };
