// ============================================================
// ALERT TYPES — Every possible alert type
// ============================================================

const ALERT_TYPES = {
  OVERDUE_RETURN:             'OVERDUE_RETURN',
  MAINTENANCE_DUE:            'MAINTENANCE_DUE',
  LOW_STOCK:                  'LOW_STOCK',
  UNAUTHORIZED_ACCESS:        'UNAUTHORIZED_ACCESS',
  FAILED_LOGIN:               'FAILED_LOGIN',
  EQUIPMENT_LOST:             'EQUIPMENT_LOST',
  EQUIPMENT_MISSING:          'EQUIPMENT_MISSING',
  ANOMALY_DETECTED:           'ANOMALY_DETECTED',
  GEOFENCE_BREACH:            'GEOFENCE_BREACH',
  TRANSFER_PENDING_APPROVAL:  'TRANSFER_PENDING_APPROVAL',
  ESCALATION_REQUIRED:        'ESCALATION_REQUIRED',
  EQUIPMENT_DAMAGED:          'EQUIPMENT_DAMAGED',
  BATTERY_LOW_TRACKER:        'BATTERY_LOW_TRACKER',
  ACCOUNT_LOCKED:             'ACCOUNT_LOCKED',
};

const AUDIT_ACTIONS = {
  // Auth
  LOGIN_SUCCESS:                   'LOGIN_SUCCESS',
  LOGIN_FAILED:                    'LOGIN_FAILED',
  LOGOUT:                          'LOGOUT',
  TOKEN_REFRESHED:                 'TOKEN_REFRESHED',
  PASSWORD_CHANGED:                'PASSWORD_CHANGED',
  ACCOUNT_LOCKED:                  'ACCOUNT_LOCKED',
  BIOMETRIC_SUCCESS:               'BIOMETRIC_SUCCESS',
  BIOMETRIC_FAILED:                'BIOMETRIC_FAILED',

  // Equipment
  EQUIPMENT_CREATED:               'EQUIPMENT_CREATED',
  EQUIPMENT_UPDATED:               'EQUIPMENT_UPDATED',
  EQUIPMENT_DELETED:               'EQUIPMENT_DELETED',
  EQUIPMENT_STATUS_CHANGED:        'EQUIPMENT_STATUS_CHANGED',
  QR_CODE_GENERATED:               'QR_CODE_GENERATED',

  // Checkout
  EQUIPMENT_CHECKOUT:              'EQUIPMENT_CHECKOUT',
  EQUIPMENT_CHECKIN:               'EQUIPMENT_CHECKIN',
  CHECKOUT_OVERDUE:                'CHECKOUT_OVERDUE',
  CHECKOUT_ESCALATED:              'CHECKOUT_ESCALATED',

  // Maintenance
  MAINTENANCE_SCHEDULED:           'MAINTENANCE_SCHEDULED',
  MAINTENANCE_STARTED:             'MAINTENANCE_STARTED',
  MAINTENANCE_COMPLETED:           'MAINTENANCE_COMPLETED',

  // Transfer
  TRANSFER_REQUESTED:              'TRANSFER_REQUESTED',
  TRANSFER_APPROVED:               'TRANSFER_APPROVED',
  TRANSFER_DISPATCHED:             'TRANSFER_DISPATCHED',
  TRANSFER_RECEIVED:               'TRANSFER_RECEIVED',
  TRANSFER_REJECTED:               'TRANSFER_REJECTED',

  // Incidents
  INCIDENT_REPORTED:               'INCIDENT_REPORTED',
  INCIDENT_UPDATED:                'INCIDENT_UPDATED',
  INCIDENT_CLOSED:                 'INCIDENT_CLOSED',

  // Alerts
  ALERT_CREATED:                   'ALERT_CREATED',
  ALERT_ACKNOWLEDGED:              'ALERT_ACKNOWLEDGED',
  ALERT_RESOLVED:                  'ALERT_RESOLVED',
  ALERT_DISMISSED:                 'ALERT_DISMISSED',

  // Admin
  USER_CREATED:                    'USER_CREATED',
  USER_UPDATED:                    'USER_UPDATED',
  USER_DEACTIVATED:                'USER_DEACTIVATED',
  ROLE_CHANGED:                    'ROLE_CHANGED',

  // System
  ANOMALY_DETECTED:                'ANOMALY_DETECTED',
  UNAUTHORIZED_ACCESS_ATTEMPT:     'UNAUTHORIZED_ACCESS_ATTEMPT',
  OFFLINE_SYNC_COMPLETED:          'OFFLINE_SYNC_COMPLETED',
  AUDIT_LOG_EXPORTED:              'AUDIT_LOG_EXPORTED',
  SYSTEM_HEALTH_CHECK:             'SYSTEM_HEALTH_CHECK',
};

module.exports = { ALERT_TYPES, AUDIT_ACTIONS };
