// ============================================================
// ROLE PERMISSIONS — Maps each role to its permission array
// ============================================================

const { ROLES }       = require('./roles');
const { PERMISSIONS } = require('./permissions');

const P = PERMISSIONS;

const ROLE_PERMISSIONS = {
  [ROLES.SOLDIER]: [
    P.EQUIPMENT_VIEW,
    P.CHECKOUT_VIEW,
    P.CHECKOUT_CREATE,
    P.CHECKOUT_CHECKIN,
    P.PERSONNEL_VIEW,
    P.INCIDENT_REPORT,
    P.ALERT_VIEW,
    P.LOCATION_PING,
  ],

  [ROLES.OFFICER]: [
    P.EQUIPMENT_VIEW,
    P.CHECKOUT_VIEW,
    P.CHECKOUT_CREATE,
    P.CHECKOUT_CHECKIN,
    P.CHECKOUT_APPROVE,
    P.CHECKOUT_VIEW_ALL,
    P.CHECKOUT_TRANSFER,
    P.PERSONNEL_VIEW,
    P.INCIDENT_REPORT,
    P.INCIDENT_VIEW,
    P.ALERT_VIEW,
    P.ALERT_ACKNOWLEDGE,
    P.TRANSFER_VIEW,
    P.TRANSFER_REQUEST,
    P.TRANSFER_APPROVE,
    P.TRANSFER_RECEIVE,
    P.LOCATION_PING,
    P.LOCATION_VIEW,
    P.MAINTENANCE_VIEW,
    P.REPORT_VIEW,
  ],

  [ROLES.TECHNICIAN]: [
    P.EQUIPMENT_VIEW,
    P.EQUIPMENT_UPDATE,
    P.MAINTENANCE_VIEW,
    P.MAINTENANCE_CREATE,
    P.MAINTENANCE_UPDATE,
    P.MAINTENANCE_SCHEDULE,
    P.MAINTENANCE_SIGN_OFF,
    P.ALERT_VIEW,
    P.ALERT_ACKNOWLEDGE,
    P.INCIDENT_VIEW,
  ],

  [ROLES.QUARTERMASTER]: [
    P.EQUIPMENT_VIEW,
    P.EQUIPMENT_CREATE,
    P.EQUIPMENT_UPDATE,
    P.EQUIPMENT_DELETE,
    P.EQUIPMENT_EXPORT,
    P.EQUIPMENT_IMPORT,
    P.EQUIPMENT_QR_GENERATE,
    P.CHECKOUT_VIEW,
    P.CHECKOUT_VIEW_ALL,
    P.CHECKOUT_CREATE,
    P.CHECKOUT_CHECKIN,
    P.CHECKOUT_APPROVE,
    P.CHECKOUT_TRANSFER,
    P.PERSONNEL_VIEW,
    P.MAINTENANCE_VIEW,
    P.MAINTENANCE_CREATE,
    P.MAINTENANCE_UPDATE,
    P.MAINTENANCE_SCHEDULE,
    P.TRANSFER_VIEW,
    P.TRANSFER_REQUEST,
    P.TRANSFER_APPROVE,
    P.TRANSFER_DISPATCH,
    P.TRANSFER_RECEIVE,
    P.INCIDENT_VIEW,
    P.INCIDENT_REPORT,
    P.INCIDENT_INVESTIGATE,
    P.ALERT_VIEW,
    P.ALERT_ACKNOWLEDGE,
    P.ALERT_RESOLVE,
    P.REPORT_VIEW,
    P.REPORT_GENERATE,
    P.LOCATION_VIEW,
    P.SEARCH_AI,
  ],

  [ROLES.AUDITOR]: [
    P.EQUIPMENT_VIEW,
    P.EQUIPMENT_EXPORT,
    P.CHECKOUT_VIEW,
    P.CHECKOUT_VIEW_ALL,
    P.PERSONNEL_VIEW,
    P.MAINTENANCE_VIEW,
    P.TRANSFER_VIEW,
    P.INCIDENT_VIEW,
    P.ALERT_VIEW,
    P.AUDIT_VIEW,
    P.AUDIT_EXPORT,
    P.REPORT_VIEW,
    P.REPORT_GENERATE,
    P.REPORT_EXPORT,
    P.LOCATION_VIEW,
    P.SEARCH_AI,
  ],

  [ROLES.BASE_ADMIN]: [
    // All permissions except SUPER_ADMIN system config
    ...Object.values(P).filter(p => p !== P.ADMIN_SYSTEM_CONFIG),
  ],

  [ROLES.SUPER_ADMIN]: Object.values(P),
};

/**
 * Returns true if the given role has at least one of the required permissions
 */
function hasAnyPermission(role, requiredPermissions = []) {
  const rolePerms = ROLE_PERMISSIONS[role] || [];
  return requiredPermissions.some(p => rolePerms.includes(p));
}

module.exports = { ROLE_PERMISSIONS, hasAnyPermission };
