// ============================================================
// STATUS TYPES — All status enums for every domain
// ============================================================

const EQUIPMENT_STATUS = {
  OPERATIONAL:       'OPERATIONAL',
  CHECKED_OUT:       'CHECKED_OUT',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  LOST:              'LOST',
  MISSING:           'MISSING',
  DECOMMISSIONED:    'DECOMMISSIONED',
  FLAGGED:           'FLAGGED',
  IN_TRANSIT:        'IN_TRANSIT',
};

const EQUIPMENT_CONDITION = {
  EXCELLENT: 'EXCELLENT',
  GOOD:      'GOOD',
  FAIR:      'FAIR',
  POOR:      'POOR',
  DAMAGED:   'DAMAGED',
};

const CHECKOUT_STATUS = {
  ACTIVE:    'ACTIVE',
  RETURNED:  'RETURNED',
  OVERDUE:   'OVERDUE',
  LOST:      'LOST',
  ESCALATED: 'ESCALATED',
};

const CHECKOUT_PURPOSE = {
  MISSION:     'MISSION',
  TRAINING:    'TRAINING',
  MAINTENANCE: 'MAINTENANCE',
  INSPECTION:  'INSPECTION',
  EXERCISE:    'EXERCISE',
  EMERGENCY:   'EMERGENCY',
};

const MAINTENANCE_TYPE = {
  ROUTINE:     'ROUTINE',
  EMERGENCY:   'EMERGENCY',
  CALIBRATION: 'CALIBRATION',
  INSPECTION:  'INSPECTION',
  OVERHAUL:    'OVERHAUL',
  REPAIR:      'REPAIR',
};

const MAINTENANCE_STATUS = {
  SCHEDULED:   'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED:   'COMPLETED',
  OVERDUE:     'OVERDUE',
  CANCELLED:   'CANCELLED',
};

const TRANSFER_TYPE = {
  INTER_UNIT:         'INTER_UNIT',
  INTER_BASE:         'INTER_BASE',
  TEMPORARY_LOAN:     'TEMPORARY_LOAN',
  PERMANENT_TRANSFER: 'PERMANENT_TRANSFER',
};

const TRANSFER_STATUS = {
  PENDING:           'PENDING',
  APPROVED_SENDER:   'APPROVED_SENDER',
  APPROVED_RECEIVER: 'APPROVED_RECEIVER',
  FULLY_APPROVED:    'FULLY_APPROVED',
  DISPATCHED:        'DISPATCHED',
  IN_TRANSIT:        'IN_TRANSIT',
  RECEIVED:          'RECEIVED',
  REJECTED:          'REJECTED',
  CANCELLED:         'CANCELLED',
};

const INCIDENT_TYPE = {
  DAMAGED:  'DAMAGED',
  LOST:     'LOST',
  STOLEN:   'STOLEN',
  DESTROYED:'DESTROYED',
  FOUND:    'FOUND',
  TAMPERED: 'TAMPERED',
};

const INCIDENT_STATUS = {
  OPEN:                'OPEN',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  RESOLVED:            'RESOLVED',
  CLOSED:              'CLOSED',
  ESCALATED:           'ESCALATED',
};

const ALERT_SEVERITY = {
  LOW:      'LOW',
  MEDIUM:   'MEDIUM',
  HIGH:     'HIGH',
  CRITICAL: 'CRITICAL',
};

const ALERT_STATUS = {
  OPEN:         'OPEN',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  RESOLVED:     'RESOLVED',
  ESCALATED:    'ESCALATED',
  DISMISSED:    'DISMISSED',
};

const AUDIT_SEVERITY = {
  INFO:      'INFO',
  WARNING:   'WARNING',
  CRITICAL:  'CRITICAL',
  EMERGENCY: 'EMERGENCY',
};

const DEVICE_TYPE = {
  WEB:    'WEB',
  MOBILE: 'MOBILE',
  SYSTEM: 'SYSTEM',
};

const CUSTODY_EVENT = {
  INITIAL_ENTRY:             'INITIAL_ENTRY',
  CHECKED_OUT:               'CHECKED_OUT',
  RETURNED:                  'RETURNED',
  TRANSFERRED:               'TRANSFERRED',
  REPORTED_LOST:             'REPORTED_LOST',
  REPORTED_MISSING:          'REPORTED_MISSING',
  SENT_FOR_MAINTENANCE:      'SENT_FOR_MAINTENANCE',
  RETURNED_FROM_MAINTENANCE: 'RETURNED_FROM_MAINTENANCE',
  DECOMMISSIONED:            'DECOMMISSIONED',
  FLAGGED:                   'FLAGGED',
  RECOVERED:                 'RECOVERED',
};

module.exports = {
  EQUIPMENT_STATUS,
  EQUIPMENT_CONDITION,
  CHECKOUT_STATUS,
  CHECKOUT_PURPOSE,
  MAINTENANCE_TYPE,
  MAINTENANCE_STATUS,
  TRANSFER_TYPE,
  TRANSFER_STATUS,
  INCIDENT_TYPE,
  INCIDENT_STATUS,
  ALERT_SEVERITY,
  ALERT_STATUS,
  AUDIT_SEVERITY,
  DEVICE_TYPE,
  CUSTODY_EVENT,
};
